service: lunch-and-learn-logger
frameworkVersion: ">=1.34.0 <2.0.0"
plugins:
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs10.x
package:
  include:
    - src/
  exclude:
    - src/**/*.spec.(t|j)s
functions:
  example:
    handler: src/handlers.handlerExample
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: loggerExample
          method: get
          cors: true
          private: false
